# Ceci indique à AWS CodeDeploy la version du format appspec que nous utilisons
version: 0.0

# Ceci spécifie que notre application s'exécutera sur un serveur Linux
os: linux

# Cette section indique à CodeDeploy où copier nos fichiers d'application
files:
  # Copier tout le code source (/) vers ce dossier sur le serveur
  - source: /
    destination: /home/ec2-user/simple-webapp

# Ce sont des scripts qui s'exécutent à différentes étapes du déploiement
hooks:
  # Ce script s'exécute d'abord pour arrêter toute version existante de notre application
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 20 # Lui donner 20 secondes pour arrêter, sinon échouer

  # Ce script s'exécute deuxièmement pour installer les logiciels/dépendances nécessaires
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300 # Lui donner 5 minutes pour tout installer

  # Ce script s'exécute en dernier pour démarrer la nouvelle version de notre application
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60 # Lui donner 1 minute pour démarrer, sinon échouer
